
name: booking
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  equatable: ^2.0.5
  # State Management
  flutter_bloc: ^8.1.5
  # Routing
  go_router: ^14.1.0
  # Service Locator
  get_it: ^7.7.0
  # Local Storage
  shared_preferences: ^2.2.3
  # Networking
  dio: ^5.4.3+1
  # Calendar
  table_calendar: ^3.1.2
  intl: ^0.19.0
  # Supabase
  supabase_flutter: ^2.5.5
  # PDF
  pdf: ^3.11.0
  open_filex: ^4.4.0
  file_saver: ^0.3.1
  hijri_calendar: ^1.0.7+7
  hijri: ^3.0.0
  logger: ^2.6.2
  mailer: ^6.0.0
  path_provider: ^2.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/fullLogo.ico"
  min_sdk_android: 21 # مهم عشان الأندرويد الحديث

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/notosans/
    - assets/fonts/diin/
    - .env # <-- أضف هذا السطر لتعريف الملف

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/notosans/NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/notosans/NotoSansArabic-Bold.ttf
          weight: 700 

    - family: DINNextLTArabic
      fonts:
        - asset: assets/fonts/diin/DINNextLTArabic-Regular-2.ttf
          weight: 400
